steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
          'us-central1-docker.pkg.dev/loxol-376616/amazon-system-repo/amazon-system-image',
          '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
          'us-central1-docker.pkg.dev/loxol-376616/amazon-system-repo/amazon-system-image']
